services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver ${DJANGO_HOST:-0.0.0.0}:${DJANGO_PORT:-8000}"
    volumes:
      - ./bookapi:/app/bookapi
    ports:
      - "${EXTERNAL_PORT:-8000}:${DJANGO_PORT:-8000}"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
