apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
stringData:
  DJANGO_SECRET_KEY: "{{ .Values.env.DJANGO_SECRET_KEY }}"
  POSTGRES_PASSWORD: "{{ .Values.env.POSTGRES_PASSWORD }}"
